### ISSUE TITLE
module declares its path as: github.com/gowarden/zflag

### ISSUE THREAD

**Issue by ghostsquad** [gowarden/pflag#3]
```
at 14:35:03 ❯ go get github.com/zulucmd/zflag
go: downloading github.com/zulucmd/zflag v0.0.0-20220216055741-dbb9069bdf21
go: github.com/zulucmd/zflag@v0.0.0-20220216055741-dbb9069bdf21: parsing go.mod:
	module declares its path as: github.com/gowarden/zflag
	        but was required as: github.com/zulucmd/zflag
```

**Comment by stefansundin** [comment]
I filed https://github.com/zulucmd/zflag/pull/2 in April. No response. I just updated my fork to be a proper fork. Didn't really want to do it but oh well.

**Comment by hoshsadiq** [comment]
Sorry for being AWOL. I started this with good intentions, but, unfortunately, life happens. I should be back on this now for the foreseeable future.

The reason for the wrong import path was that it was originally supposed to be on a different org, but then decided to have it in its own org.
